specVersion: "1.0.0"

name: "crabada-nft"
version: "0.0.1"
runner:
  node:
    name: "@subql/node-ethereum"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: "This project indexes all Crabada NFTs on Avalanche's C-chain"
repository: "https://github.com/jamesbayly/crabada-nft-indexer"

schema:
  file: "./schema.graphql"

network:
  # chainId is the EVM Chain ID, for Avalanche-C chain is 43114
  # https://chainlist.org/chain/43114
  chainId: "43114"
  # This endpoint must be a public non-pruned archive node
  # We recommend providing more than one endpoint for improved reliability, performance, and uptime
  # Public nodes may be rate limited, which can affect indexing speed
  # When developing your project we suggest getting a private API key
  # You can get them from OnFinality for free https://app.onfinality.io
  # https://documentation.onfinality.io/support/the-enhanced-api-service
  endpoint:
    - https://avalanche.api.onfinality.io/public/ext/bc/C/rpc
  # Recommended to provide the HTTP endpoint of a full chain dictionary to speed up processing
  dictionary: "https://api.subquery.network/sq/subquery/avalanche-dictionary"

dataSources:
  - kind: ethereum/Runtime # We use ethereum runtime since Avalanche is compatible
    startBlock: 30558382
    # startBlock: 29990399 # Contract creation of Crabada legacy https://snowtrace.io/tx/0x3022e7df2873f0112a594fda44f8d8a7d83e17e21d177f3013048a1f579bc09e
    options:
      # Must be a key of assets
      abi: erc721
      ## Crabada Legacy Contract https://snowtrace.io/address/0xCB7569a6Fe3843c32512d4F3AB35eAE65bd1D50c
      address: "0xCB7569a6Fe3843c32512d4F3AB35eAE65bd1D50c"
    assets:
      erc721:
        file: "./abis/erc721.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleERC721
          kind: ethereum/LogHandler
          filter:
            topics:
              - Transfer(address from, address to, uint256 tokenId)
